/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author rasyi
 */
public class aplikasiPenghitungKata extends javax.swing.JFrame {

    /**
     * Creates new form aplikasiPenghitungKata
     */
    public aplikasiPenghitungKata() {
        initComponents();
        
        txtInput.getDocument().addDocumentListener(new DocumentListener() {
        @Override
        public void insertUpdate(DocumentEvent e) {
            hitungOtomatis();
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            hitungOtomatis();
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            hitungOtomatis();
        }
    });
    }

    private void hitungOtomatis() {
    String teks = txtInput.getText();
    String teksTrim = teks.trim();

    // Hitung jumlah kata
    String[] kata = teksTrim.split("\\s+");
    int jumlahKata = teksTrim.isEmpty() ? 0 : kata.length;

    // Hitung karakter tanpa spasi
    int jumlahKarakter = teks.replaceAll("\\s", "").length();

    // Hitung spasi
    int jumlahSpasi = 0;
    for (int i = 0; i < teks.length(); i++) {
        if (Character.isWhitespace(teks.charAt(i))) {
            jumlahSpasi++;
        }
    }

    // Hitung tanda baca
    int jumlahTandaBaca = 0;
    for (int i = 0; i < teks.length(); i++) {
        char c = teks.charAt(i);
        if (!Character.isLetterOrDigit(c) && !Character.isWhitespace(c)) {
            jumlahTandaBaca++;
        }
    }

    // Hitung kalimat
    String[] kalimat = teksTrim.split("[.!?]+");
    int jumlahKalimat = teksTrim.isEmpty() ? 0 : kalimat.length;

    // Hitung paragraf
    String[] paragraf = teksTrim.split("\\n+");
    int jumlahParagraf = teksTrim.isEmpty() ? 0 : paragraf.length;

    // Total keseluruhan karakter (semua termasuk spasi & tanda baca)
    int totalKeseluruhan = teks.length();

    // 🔹 Tampilkan hasil ke label
    lblJumlahKata.setText(String.valueOf(jumlahKata));
    lblJumlahKarakter.setText(String.valueOf(jumlahKarakter));
    lblJumlahKalimat.setText(String.valueOf(jumlahKalimat));
    lblJumlahParagraf.setText(String.valueOf(jumlahParagraf));
    lblJumlahSpasi.setText(String.valueOf(jumlahSpasi));
    lblJumlahTandaBaca.setText(String.valueOf(jumlahTandaBaca));
    lblTotalKeseluruhan.setText(String.valueOf(totalKeseluruhan));
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInput = new javax.swing.JTextArea();
        btnHitung = new javax.swing.JButton();
        lblJumlahKata = new javax.swing.JLabel();
        lblJumlahKalimat = new javax.swing.JLabel();
        lblJumlahKarakter = new javax.swing.JLabel();
        lblJumlahParagraf = new javax.swing.JLabel();
        lblJumlahKata1 = new javax.swing.JLabel();
        lblJumlahKarakter1 = new javax.swing.JLabel();
        lblJumlahKalimat1 = new javax.swing.JLabel();
        lblJumlahParagraf1 = new javax.swing.JLabel();
        lblJumlahSpasi1 = new javax.swing.JLabel();
        lblJumlahSpasi = new javax.swing.JLabel();
        lblJumlahTandaBaca1 = new javax.swing.JLabel();
        lblJumlahTandaBaca = new javax.swing.JLabel();
        lblTotalKeseluruhan1 = new javax.swing.JLabel();
        lblTotalKeseluruhan = new javax.swing.JLabel();
        lblTotalKeseluruhan2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("APLIKASI PENGHITUNG KATA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtInput.setColumns(20);
        txtInput.setLineWrap(true);
        txtInput.setRows(5);
        txtInput.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtInput);

        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        lblJumlahKata.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblJumlahKalimat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblJumlahKarakter.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblJumlahParagraf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblJumlahKata1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblJumlahKata1.setText("Jumlah Kata         :");

        lblJumlahKarakter1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblJumlahKarakter1.setText("Jumlah Karakter        :");

        lblJumlahKalimat1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblJumlahKalimat1.setText("Jumlah Kalimat    :");

        lblJumlahParagraf1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblJumlahParagraf1.setText("Jumlah Paragraf       :");

        lblJumlahSpasi1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblJumlahSpasi1.setText("Jumlah Spasi        :");

        lblJumlahSpasi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblJumlahTandaBaca1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblJumlahTandaBaca1.setText("Jumlah  Tanda Baca  :");

        lblJumlahTandaBaca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblTotalKeseluruhan1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalKeseluruhan1.setText("Total Keseluruhan Karakter , Spasi, Dan Tanda Baca     :");

        lblTotalKeseluruhan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblTotalKeseluruhan2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalKeseluruhan2.setText("Pencarian   :");

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTotalKeseluruhan2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCari))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addComponent(btnHitung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(5, 5, 5)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(lblJumlahKalimat1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                                .addComponent(lblJumlahKata1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblJumlahKata, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblJumlahKalimat, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(30, 30, 30)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(lblJumlahParagraf1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblJumlahKarakter1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)))
                                        .addComponent(lblTotalKeseluruhan1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(12, 12, 12)
                                            .addComponent(lblTotalKeseluruhan, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(16, 16, 16)
                                            .addComponent(lblJumlahKarakter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(16, 16, 16)
                                            .addComponent(lblJumlahParagraf, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblJumlahSpasi1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblJumlahSpasi, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(lblJumlahTandaBaca1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblJumlahTandaBaca, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(23, 23, 23))))
                .addContainerGap(11, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalKeseluruhan2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari))
                .addGap(23, 23, 23)
                .addComponent(btnHitung)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJumlahKata, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJumlahKarakter, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJumlahKata1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJumlahKarakter1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJumlahTandaBaca1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJumlahSpasi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJumlahSpasi1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJumlahTandaBaca, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJumlahParagraf1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJumlahKalimat, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJumlahKalimat1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJumlahParagraf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotalKeseluruhan1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalKeseluruhan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnKeluar))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:
       hitungOtomatis(); 
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
            JFileChooser chooser = new JFileChooser();
    chooser.setDialogTitle("Simpan hasil ke file teks (.txt)");
    int userSelection = chooser.showSaveDialog(this);

    if (userSelection == JFileChooser.APPROVE_OPTION) {
        File fileToSave = chooser.getSelectedFile();

        // Tambahkan ekstensi .txt jika belum ada
        if (!fileToSave.getAbsolutePath().toLowerCase().endsWith(".txt")) {
            fileToSave = new File(fileToSave.getAbsolutePath() + ".txt");
        }

        try (BufferedWriter writer = new BufferedWriter(new FileWriter(fileToSave))) {
            writer.write("=== APLIKASI PENGHITUNG KATA ===\n\n");
            writer.write("Teks Asli:\n" + txtInput.getText() + "\n\n");
            writer.write("=== HASIL PERHITUNGAN ===\n");
            writer.write("Jumlah Kata               : " + lblJumlahKata.getText() + "\n");
            writer.write("Jumlah Karakter (tanpa spasi): " + lblJumlahKarakter.getText() + "\n");
            writer.write("Jumlah Spasi              : " + lblJumlahSpasi.getText() + "\n");
            writer.write("Jumlah Tanda Baca         : " + lblJumlahTandaBaca.getText() + "\n");
            writer.write("Jumlah Kalimat            : " + lblJumlahKalimat.getText() + "\n");
            writer.write("Jumlah Paragraf           : " + lblJumlahParagraf.getText() + "\n");
            writer.write("Total Keseluruhan Karakter: " + lblTotalKeseluruhan.getText() + "\n");
            writer.write("\nFile disimpan di: " + fileToSave.getAbsolutePath());

            JOptionPane.showMessageDialog(this,
                    "Berhasil disimpan di:\n" + fileToSave.getAbsolutePath(),
                    "Sukses", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this,
                    "Gagal menyimpan file: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
         String teks = txtInput.getText().toLowerCase();
    String cari = jTextField1.getText().toLowerCase();

    if (cari.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Masukkan kata yang ingin dicari!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }

    String[] kata = teks.split("\\s+");
    int jumlahDitemukan = 0;

    for (String k : kata) {
        if (k.equals(cari)) {
            jumlahDitemukan++;
        }
    }

    JOptionPane.showMessageDialog(this,
        "Kata \"" + cari + "\" ditemukan sebanyak " + jumlahDitemukan + " kali.",
        "Hasil Pencarian", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnCariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(aplikasiPenghitungKata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(aplikasiPenghitungKata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(aplikasiPenghitungKata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(aplikasiPenghitungKata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new aplikasiPenghitungKata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblJumlahKalimat;
    private javax.swing.JLabel lblJumlahKalimat1;
    private javax.swing.JLabel lblJumlahKarakter;
    private javax.swing.JLabel lblJumlahKarakter1;
    private javax.swing.JLabel lblJumlahKata;
    private javax.swing.JLabel lblJumlahKata1;
    private javax.swing.JLabel lblJumlahParagraf;
    private javax.swing.JLabel lblJumlahParagraf1;
    private javax.swing.JLabel lblJumlahSpasi;
    private javax.swing.JLabel lblJumlahSpasi1;
    private javax.swing.JLabel lblJumlahTandaBaca;
    private javax.swing.JLabel lblJumlahTandaBaca1;
    private javax.swing.JLabel lblTotalKeseluruhan;
    private javax.swing.JLabel lblTotalKeseluruhan1;
    private javax.swing.JLabel lblTotalKeseluruhan2;
    private javax.swing.JTextArea txtInput;
    // End of variables declaration//GEN-END:variables
}
